apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: campaign-statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: name
scopes:
  - campaign-manager-notifier
  - campaign-manager-externalizer
  - campaign-manager-institution
  - campaign-manager-campaign
  - campaign-manager-member
  - campaign-manager-membership
