apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: campaign-statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: name
scopes:
  - institution-manager-notifier
  - institution-manager-externalizer
  - institution-manager-institution
  - institution-manager-campaign
  - institution-manager-member
  - institution-manager-membership
  - institution-manager-htmx
