apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: campaign-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  # Do not include a consumer group so that the DAPR runtime sets it to APPID
  - name: enableTLS
    value: "false"
scopes:
  - campaign-manager-notifier
  - campaign-manager-externalizer
  - campaign-manager-institution
  - campaign-manager-campaign
  - campaign-manager-member
  - campaign-manager-membership
